### ISSUE TITLE
Vue project erstellen

### ISSUE THREAD

**Issue by joegregory-cbe** [coding-bootcamps-eu/final-project-2023-09-kamp#1]
# Anforderungen

- [x] Installation eines Vue Projektes mit [create-vue](https://vuejs.org/guide/quick-start#creating-a-vue-application)
  - [x] Eslint & Prettier
  - [x] Router
  - [x] Pinia
- [x] Entfernen aller Dummy Dateien von create-vue
  - [x] Alle Dateien im src/assets folder
  - [x] Alle Dateien im src/components folder
  - [x] main.css aus main.js entfernen
  - [x] app vue von dummy code entfernen
  - [x] Ausgabe des Projekt namens in der Home vue
- [x]  Push in den main branch

**Comment by czeopauli** [comment]
Alle Punkte erledigt
